DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS voice_uploads;
DROP TABLE IF EXISTS reports;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS admin_users;
DROP TABLE IF EXISTS refresh_tokens;